language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update
  - pip install --user codecov

install:
  - composer install

script:
  - php vendor/bin/phpunit
  
after_success:
  - codecov
